version: '3'

services:

  rest-api:
    build: 
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    env_file:
      - ./.env.backend
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env.frontend
    
    volumes:
    - /opt/app/node_modules
    - ./frontend:/opt/app


  database:
    restart: always
    image: "bitnami/mongodb:latest"
    volumes:
      - ./db/mongodb-data:/var/lib/mongodb/data
    ports:
      - 27017:27017
    env_file:
      - ./.env.db
  
  chatbot:
    restart: always
    build: 
      context: "./ai"
      dockerfile: Dockerfile
    ports:
      - "5001:5001"


volumes:
  mongodb-data: