version: '3'

services:

  rest-api:
    build: 
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    environment:
      - MONGODB_HOST=database
      - MONGODB_DATABASE=db
      - MONGODB_PORT=27017

  database:
    restart: always
    image: "bitnami/mongodb:latest"
    volumes:
      - ./db/mongodb-data:/var/lib/mongodb/data
    environment:
      - MONGODB_DATABASE=db
    ports:
      - 27017:27017

volumes:
  mongodb-data: